Added get_django_setting and updated runserver create_apache_vhost_conf.sh

diff --git a/scripts/initenv_generic b/scripts/initenv_generic
--- a/scripts/initenv_generic
+++ b/scripts/initenv_generic
@@ -18,15 +18,15 @@ _deactivate() {
 
 # The root of the project should exist, of course
 [ -z "$PROJECT_ROOT" ] && \
-    echo "Variable PROJECT_ROOT not set or empty" 2>&1 && _deactivate && return 1
+    echo "Variable PROJECT_ROOT not set or empty" 1>&2 && _deactivate && return 1
 [ ! -d "$PROJECT_ROOT" ] && \
-     echo "Variable PROJECT_ROOT does not point to a readable directory" 2>&1 && _deactivate && return 1
+     echo "Variable PROJECT_ROOT does not point to a readable directory" 1>&2 && _deactivate && return 1
 
 # Check Django project as well
 [ -z "$DJANGO_PROJECT" ] && \
-    echo "Variable DJANGO_PROJECT not set or empty" 2>&1 && _deactivate && return 1
+    echo "Variable DJANGO_PROJECT not set or empty" 1>&2 && _deactivate && return 1
 [ ! -d "$PROJECT_ROOT/$DJANGO_PROJECT" ] && \
-    echo "Variable DJANGO_PROJECT does not identify a readable directory within $PROJECT_ROOT" 2>&1 && \
+    echo "Variable DJANGO_PROJECT does not identify a readable directory within $PROJECT_ROOT" 1>&2 && \
     _deactivate && return 1
 
 # If no particular settings are defined, just use the "base" settings
@@ -44,9 +44,9 @@ PYTHONPATH=$PROJECT_ROOT:$1:$PYTHONPATH
 export PROJECT_ROOT DJANGO_PROJECT PYTHONPATH DJANGO_SETTINGS_MODULE
 
 # Test settings import
-python -c "import $DJANGO_SETTINGS_MODULE" > /dev/null 2>&1
+python -c "import $DJANGO_SETTINGS_MODULE" > /dev/null 1>&2
 if [ ! "$?" -eq 0 ]; then
-    echo "Error importing settings $DJANGO_SETTINGS_MODULE (PYTHONPATH: $PYTHONPATH)" 2>&1
+    echo "Error importing settings $DJANGO_SETTINGS_MODULE (PYTHONPATH: $PYTHONPATH)" 1>&2
     python -c "import $DJANGO_SETTINGS_MODULE"
     _deactivate
     return 1
@@ -67,43 +67,24 @@ fi
 
 # Some useful functions
 
-# Change directory to project root
-function cdroot() {
-    cd $PROJECT_ROOT/$1
-}
+# Get a django setting from the current settings module
+# Experimental.
+#
+# Example:
+# LC=`get_django_setting LANGUAGE_CODE` && echo $LC
+# 
+# Returns nothing if setting cannot be found
+function get_django_setting() {
+    [ -z "$1" ] && echo "Supply setting name" 1>&2 && return 1
 
-# Change directory to django project
-function cdjango () {
-    cd $PROJECT_ROOT/$DJANGO_PROJECT/$1
-}
+    python << EOF
+import $DJANGO_SETTINGS_MODULE as settings
 
-# Install dependencies for an environment (first argument); the file
-# with the dependencies should be in the requirements directory and
-# should have the format 'libs-<environment>.txt'
-function pipup() {
-    if [ -z "$1" ]; then
-        echo Usage: pipup '<requirements-identifier>'
-        return 1
-    else
-        pip install --requirement=$PROJECT_ROOT/requirements/libs-$1.txt
-    fi
-}
-
-# Remove .pyc files without a corresponding .py
-function removeorphanpycs() {
-    for pyc in `find . -name \*.pyc`; do
-        [ -f  `echo $pyc | sed 's/c$//'` ] || rm -v $pyc
-    done
-}
-
-# Forget manage.py, django-admin.py respects our settings!
-function djadmin() {
-    django-admin.py $*
-}
-
-# Run development server on settings.LOCAL_SERVER_PORT
-function runserver() {
-    django-admin.py runserver `$PROJECT_ROOT/scripts/get_local_server_port.py`
+try:
+    print settings.__dict__['$1']
+except KeyError:
+    pass
+EOF
 }
 
 # Import django settings into the shell environment
@@ -151,8 +132,47 @@ for name, value in settings:
 EOF
 }
 
+# Change directory to project root
+function cdroot() {
+    cd $PROJECT_ROOT/$1
+}
+
+# Change directory to django project
+function cdjango () {
+    cd $PROJECT_ROOT/$DJANGO_PROJECT/$1
+}
+
+# Install dependencies for an environment (first argument); the file
+# with the dependencies should be in the requirements directory and
+# should have the format 'libs-<environment>.txt'
+function pipup() {
+    if [ -z "$1" ]; then
+        echo Usage: pipup '<requirements-identifier>'
+        return 1
+    else
+        pip install --requirement=$PROJECT_ROOT/requirements/libs-$1.txt
+    fi
+}
+
+# Remove .pyc files without a corresponding .py
+function removeorphanpycs() {
+    for pyc in `find . -name \*.pyc`; do
+        [ -f  `echo $pyc | sed 's/c$//'` ] || rm -v $pyc
+    done
+}
+
+# Forget manage.py, django-admin.py respects our settings!
+function djadmin() {
+    django-admin.py $*
+}
+
+# Run development server on settings.LOCAL_SERVER_PORT
+function runserver() {
+    django-admin.py runserver `get_django_setting LOCAL_SERVER_PORT`
+}
+
 # Export functions that are not solely intended for interactive use
-export -f import_django_settings
+export -f get_django_setting import_django_settings
 
 # Change working directory - time to party
 cdjango
